### ISSUE TITLE
Nettle download GPG keyserver broken

### ISSUE THREAD

**Issue by HonoluluHenk** [PeterPawn/decoder#25]
When executing `make`, I received the error message 'gpg: error reading key: No public key' from download.sh.

After digging around, I found that the keyserver hkp://keys.gnupg.net:11371 is not responding. 
This server does not seem to exist anymore!

Workaround:
Modify the file `src/nettle/download.sh` as follows:
Replace 
`keyServer=hkp://keys.gnupg.net:11371`
with (e.g.)
`keyServer=keyserver.ubuntu.com`
Or use some other [keyserver](https://stackoverflow.com/questions/66217436/gpg-keyserver-receive-failed-no-name)

Then make runs without errors.

**Comment by PeterPawn** [comment]
Thx for info - I'm getting annoyed to look for further key-servers (and I don't want to use one regularly, that's operated by Canonical) and so I've included the public key into the download script. This should solve the problem, too.

**Comment by PeterPawn** [comment]
closed by e8b2924e81102eda226aa7d333974606eef94d35 - the hash referenced above was the first attempt and I had to correct another mistake later.
